### ISSUE TITLE
[feat] 0526 로그인 기능 FE 협업시 생겨난 기능들 추가

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#102]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

FE와 대면으로 협업하면서 변경되거나 하는 상황 적용

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] fe와 대면으로 작업 진행시 생겨난 변경사항들 적용
   - [x] token 부를 url 설정
   - [x] 기획상 변경된 프로필 이미지 삭제에 따른 관련 코드 정리
   - [x]  급하게 요청 들어온 지역, 학교 이름들 불러오는 api 추가

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
