### ISSUE TITLE
[feat] User, School Entity의 grade 순위 및 점수에 따라 계산하여 반영

### ISSUE THREAD

**Issue by leesj000603** [capstone-kw-jjiggle/gitbal-be#104]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!
기존에 전부 NEWBIE 로 설정해 놨던 User의 점수에 따라 등급 설정
schoolGrade 컬럼 추가 및 SchoolGrade constant 추가
## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] School의 grade는 순위에 따라 기존에 기획했던 비율에 따라 등급 계산
- [x] User grade는 레벨 형식으로 기획했기 때문에 점수에 따라 등급 계산
- [x] api response에 grade 혹은 rank 담아서 보내도록 수정

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- https://www.figma.com/design/Da0jDVSu8fKxyjiMtwLndH/%ED%94%84%EB%A1%9C%ED%86%A0%ED%83%80%EC%9E%85?t=LxP4AgdIlhNCDLbw-0
