### ISSUE TITLE
[feat] 스케쥴링 적용시켜서 일정 시간마다 랭킹 갱신하는 기능 추가하기

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#107]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

일정 시간마다 랭킹을 갱신하기위한 작업을 진행한다.

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] 일정 시간 갱신 작업 진행 @Scheduler 적용시켜서 진행하기
   - [x] 유저, 학교, 지역 랭킹, 주요 언어 갱신 작업(6시간마다 임의 유저별로)
   - [x] 1일1커밋 관련 갱신작업(1일마다)
   - [x] 유저 업데이트 관련 구체적인 작업은 이슈 따로 파서 진행 #109  

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
