### ISSUE TITLE
[feat] userUpdate 관련 로직 구체화 작업

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#109]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

#107 작업 도중 발견하여 브랜치 추가로 파서 진행할 예정

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] onedayCommit 관련하여서 modifiedDate 활용하여서 전날 진행하였으면 steadyCount 더하는 방식으로 진행
   - [x] 전체적으로 BaseEntity 적용시켜서 수정 날짜, 생성 날짜 지정해놓기 
- [x] 전날이 아니었다면 연속해서 하는 steadyCount는 0으로 초기화
- [x] 이전에 사용하였던 생성 이후 주 언어에 대하여 업데이트 되었을때 갱신작업을 정의합니다.
- [x] 주요 언어 관련하여서 언어 갯수가 아니라 코드 내의 언어 size 단위로 체크하도록 변경
- [x] 주요 언어 관련 업데이트 시 주요 언어가 줄어들거나 늘었을 경우도 고려
- [x] 유저 점수 관련 작업 진행시 학교, 지역 등등 부가적으로 반영되는 요소도 처리
- [x] isp에 부합하게 인터페이스 분리
