### ISSUE TITLE
[fix] 배포 작업 진행하면서 생겼던 오류

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#117]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

docker-compose로 분리하기 시작하고 api들을 테스트해보면서 발생한 오류들에 관해 급하게 수정한 부분들입니다.

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] MockData 생성을 진행하는데 jpa delete가 제대로 동작하지 않아 따로 로직을 작성하여 중복 insert 방지
- [x] FE_URL @Value 처리
- [x] /api/v1/auth/userInfo api 관련하여 수정작업 진행 -> authentication으로 진행
   - [x] 해당 api response시 오류 발생하는 것 수정! -> @Getter 추가
- [x] scheduling 진행시 유저가 서비스에 제대로 학교, 지역을 등록하지 않아 온전한 등록 상태가 아니라면 업데이트 대상에서 제외하는 작업 진행
