### ISSUE TITLE
[fix] FE 에서 요청한 api 반환값 관련 수정작업

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#121]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

검색을 진행하였을때 넘겨주는 api에서 검색시 값이 없다면 -> 오류가 아닌 빈 리스트로 처리해달라는 요청이 있었음. 해당 사항에 대한 작업 진행

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] 검색하였을때 나오지 않았다면 오류로 처리하지 말고 빈 리스트로 전달하는 방식으로 진행
   - [x] /api/v1/mainPage/search 수정
   - [x] /api/v1/schoolRank/search 수정 
- [x] search api들을 그냥 해당 list를 불러오는 api 에 합쳐서 처리하도록 진행

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
