### ISSUE TITLE
[feat] 배포용 url로 변경 작업 진행선정

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#142]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

FE 도메인 지정으로 인한 dev, prod 관련 url 정리

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] 로컬로 사용되었던 url, 배포용으로 사용될 url 관련한 처리
- [x] redirect 관련 url 설정 변경
- [x] 배포용 환경 변수, 로컬형 환경 변수 분리작업 진행
- [x] 급한 요청으로 인한 jwt 시간 관련 배포, 로컬 환경 변수 분리작업 진행
