### ISSUE TITLE
[feat] 무중단 배포 blue-green 방식으로 구성 및 merge 되어질때만 반영되도록 수정

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#152]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

코드가 무중단 배포 되도록 진행 -> blue green 방식으로 : rolling, canary방식으로 진행하기엔 서비스의 특성과는 맞지 않음.

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [ ] ec2의 nginx 스크립트 작성 및 포워딩 구성
- [ ] docker-compose 파일 수정
- [ ] gradle.yml 파일 수정하여 merge 될때만 확인가능하게 진행

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
