### ISSUE TITLE
[refactor] 전반적인 코드 리팩토링 진행

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#154]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

전반적으로 어지럽혀졌던 코드들을 정리하고 클린코드의 방향성에 맞게 수정하여본다. 

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] 서비스 코드가 트랜잭션 스크립트였다면 -> 도메인 계층을 하나 더 둬서 로직 처리하기
- [x] repository와 같은 경우는 이후에 변경이나 확장성을 고려하여서 jpa에 종속적이지 않도록 인터페이스를 통한 의존성 끊어내는 작업 진행
- [x] 진행 도중 테스트 코드가 먼저라는 생각이 들어 테스트 코드부터 진행하고 해당 작업 추가 진행 #160 
- [x] 기획 변경으로 인한 작업 주석으로 작성한 작업을 진행한다.

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
