### ISSUE TITLE
[fix] 기획 변경에 따른 userPage 도메인 작업

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#163]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

기획 변경에 따라 간단해진 요구사항에 맞게 기존 userPage 관련 api를 수정한다.

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] api 삭제 작업 진행
- [x] api 수정사항 작업 진행
   - [x] userScore 관련 api 변경 -> userRanking 관련 작업
   - [x] school,region 관련 api 변경 -> 응답 변경 진행
   - [x] lang 관련 api 변경 -> 응답 변경 진행
  

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
