### ISSUE TITLE
[feat] 방명록 도메인 api 구축 진행

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#168]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!
방명록이라는 페이지가 새로 생김에 따라 필요한 api들 구성

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] erd에 방명록 테이블 반영
- [x] api 구축 진행
- [x] api 테스트 진행 (2개 있었기에 수동으로 테스트)
- [x] 방명록 테스트 코드 작성

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
