### ISSUE TITLE
[feat] 친구추천 기능 개발

### ISSUE THREAD

**Issue by leesj000603** [capstone-kw-jjiggle/gitbal-be#171]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!
user에게 친구추천을 제공하는 기능 구현

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [ ] 가장 높은 등급의 사람 한명
- [ ] 나랑 같은 언어를 쓰는 사람 한명
- [ ] 나보다 한 등급 높은 사람 한명
- [ ] 나랑 점수가 가장 가까운 사람 한명

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-

**Comment by leesj000603** [comment]
close
