### ISSUE TITLE
[feat] 유저 도메인 API 개발

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#20]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

유저 관련 API 개발 진행합니다.(/api/v1/join : 회원등록 , /api/v1/userInfo : 유저 정보 관련)

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [ ] user entity 생성
- [ ] user login 관련 개발 진행
   - [ ] github oauth 소셜 로그인 사용해서 진행(추후 jwt 기능 사용)
   - [ ] 임의로 등록할 대학 관련 데이터 만들어서 넣기

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- https://docs.google.com/spreadsheets/d/1RihtGhCtWh2FnMNulmEFU9hOkF_8U0lx/edit#gid=813814669
