### ISSUE TITLE
[feat] api/v1/join 기능 구현하기!

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#27]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

[api 명세서](https://docs.google.com/spreadsheets/d/1RihtGhCtWh2FnMNulmEFU9hOkF_8U0lx/edit#gid=813814669)에 나와있는데로 
과정들 진행하기

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

언제나 위쪽에 위치하도록 정렬시키는 방법
- [x] user에 대한 request 정보 가져와서 정제하는 작업
   - [x] user table 점수 계산한 값만 column으로 넣기
   - [x] school 관련 설정을 위한 로직 작성
   - [x] region 관련 설정을 위하 로직 작성
   - [x] 1일 1contribution 확인 관련 로직
   - [x] 깃허브에서 정보들을 가져와서 점수를 계산하는 과정
- [x] 임시로 데이터 만들어서 진행하기!

## 발생 이슈 상황

찾은 문제점
- [x] 유저가 여러명 들어올때 유저 1 : 광운대, 경상남도, 유저 2 : 광운대, 경상남도 -> 해당 경우 삽입이 안됨! 겹쳐진 경우 안되는 문제가 생김
   - [x] 엔티티 연관관계 매핑이 잘못되었음.
   - [x] 지역도 마찬가지임!!
- [x] language 테이블 관련하여서도 현재 테이블 설정이 잘못되어있음. 누가 어떤 값을 가지고 있는지 알아야함.  

## 고민사항
- school,region 테이블에 top contributor 같이 들어가있는데 사실 이게 맞는지 모르겠다.
   - 사실 테이블 수정을 좀 해야할 거 같음. 물론! 성능상 별로 안좋아질 수 있지만 뭔가 문맥상 맞지 않은거 같음. 

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- https://docs.github.com/en/graphql

**Comment by khyojun** [comment]
3.31 회의 내용 참고하여서 진행하기!

회의중 해당하는 도메인 업무 
- commitDate 말고 Contribution 기준으로 확인하기

https://gitbal.atlassian.net/browse/GITBAL-96?atlOrigin=eyJpIjoiOTRhMTFlMmM1ZTg4NGU5OWE1NTJkN2U0N2U4YmEwOWMiLCJwIjoiaiJ9

**Comment by khyojun** [comment]
이후에 필요한 리팩토링 및 이름 변경 사항은 다른 이슈로 파서 진행하는것으로 하겠습니다.
