### ISSUE TITLE
[feat] userRank 도메인 작업하기

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#33]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

[jira userRank](https://gitbal.atlassian.net/jira/software/projects/GITBAL/boards/1?selectedIssue=GITBAL-104)
해당 이슈 관련 API 작업 진행합니다.

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [ ] 아래 api 작업 마무리(임시 데이터 바탕으로 수행)
   - [ ] /api/v1/userRank/userscore 완성
   - [ ] /api/v1/userRank/race 완성
   - [ ] /api/v1/userRank/school 완성
   - [ ] /api/v1/userRank/region 완성
   - [ ] /api/v1/userRank/lang 완성
- [ ] 위 작업 수행 후 swagger 수정

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
