### ISSUE TITLE
[feat] userRank 도메인 /api/v1/userRank/school 구현 및 추상화에 따른 리팩토링 작업 수행

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#40]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

**/api/v1/userRank/school 구현**

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x]  /api/v1/userRank/school 구현
   - [x] 학교를 찾고 해당 학교의 위 3개 아래 3개 불러올 수 있도록 구현
   - [x] 학교별 앞에서 3등, 뒤에서 3등 했을 상황 고려
- [x] #41 브랜치 추가 생성해서 마이페이지 탭에 존재하는 주변 데이터들을 찾기 위한 추상화 과정 진행 
   - [x] Status 관련 추상화시키기 

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
