### ISSUE TITLE
[feat] api/v1/schoolRank 와 api/v1/regionRank 의 List기능 (페이징처리) 개발 

### ISSUE THREAD

**Issue by leesj000603** [capstone-kw-jjiggle/gitbal-be#47]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

학교 리스트와 지역 리스트를 페이징 처리하여 response로 보낼 수 있도록 한다.

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] MockDataGenrator에 코드 추가하여 실행 시 Region과 School 테이블에 top_contributor와 contributor_score를 계산해서 채워지도록 하기
- [x] api/v1/schoolRank/schoolList 개발
- [x] api/v1/regionRank/regionList 개발

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
