### ISSUE TITLE
[feat] /api/v1/mainPage/users 개발

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#52]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

mainPage에 나오게 될 user들에 대한 정보를 나타내기 위한 화면입니다.

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] jira 보드에 해당 작업 관련하여 반영하기
- [x] /api/v1/mainPage/users api 명세서 참고하여 응답 양식에 맞게 출력되도록 개발하기
   - [x] 현재 등급관련 로직은 아직 기획 확정되지 않아서 해당값 비우고 설정
   - [x] 페이징 처리 

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
