### ISSUE TITLE
[feat] /api/v1/mainPage/search 개발

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#54]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

mainPage에서 user를 검색할 때 어떻게 나올 지 요청하는 api입니다.

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] jira 보드에 해당 기능 관련 반영하기
- [x] /api/v1/mainPage/search api 명세서에 맞게 응답 결과 개발하기
   - [x] 페이지네이션 적용하여 진행하기

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
