### ISSUE TITLE
[feat] /api/v1/schoolRank/mySchool 개발 진행

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#65]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

스쿨랭크탭의 나의 학교 관련하여 보여주기 위한 기능

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] jira 에 작업 내용 정리하기
- [x] 명세서에 나온대로 응답 관련 정리하기
    - [x] loginUser관련하여 응답 얻어올 수 있도록 진행하기 
    - [ ] 로컬에서 임시로 백엔드끼리 토큰 가지고 테스트하는 경우까지만 수행(이후 프론트엔드 api 작업 끝날 경우 실제 연결하는 이슈 생성할 예정)

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
