### ISSUE TITLE
[feat] /api/v1/withdraw 개발 진행

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#67]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

회원 탈퇴관련하여 개발하기 위한 api 작업입니다.

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] 탈퇴 관련 작업 진행
   - [x] db에서 배제(school, region) 등등 연관요소 제거하기 
   - [x] 작업 진행할 때 로그인하고있는 유저 기준으로 하여 진행 

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
