### ISSUE TITLE
[feat] /api/v1/my/config/region 개발 진행

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#68]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

지역을 수정하기 위한 작업입니다.

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] jira에 이후에 정리하기
- [x] 지역 이름 관련 수정 작업 진행
   - [x] 해당 지역 관련 점수 변경 작업 진행 

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
