### ISSUE TITLE
[fix] Spring Security 관련 refreshToken 수정 작업 진행

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#74]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

현재 임시로 만들어놓은 refreshToken 수정 작업을 진행하기 위한 작업입니다.

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] accessToken 주기 늘리기 -> 20초에서 60초!
- [x] refreshToken으로 갱신 방법 user이름으로 찾아서 진행하는 방식으로 변경하기!
- [x] redis 키 관련하여 ttl 설정하여 만료시키기(10분 정도 설정 이후 기획에 따라 변경)
- [x] redis accessToken 관련하여서 삭제 작업, 엔티티 명 수정 작업

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
