### ISSUE TITLE
api/v1/config/school , api/v1/config/region, api/v1/profileImg, api/v1/withdraw 개발

### ISSUE THREAD

**Issue by leesj000603** [capstone-kw-jjiggle/gitbal-be#76]
## 🛠️ 작업 설명
>유저의 개인정보 수정에 관한 기능 개발 (학교 변경, 지역 변경, 프로필 사진 삭제/변경, 회원탈퇴)

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] api/v1/config/school
- [x] api/v1/config/region
- [x] api/v1/profileImg (put, delete)
- [x] api/v1/withdraw

api별로 이슈가 있었지만, 기능적으로 유사하다고 판단하여 한번에 개발

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
