### ISSUE TITLE
[feat] school에 랭킹 컬럼, 상승폭 컬럼 추가

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#78]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

검토하였을때 학교 랭킹 추가하기로 기획에서 결정나서 컬럼 추가하고 이후에 관련 api들에 해당 데이터 넣어주기로함.

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!
- [ ] /api/v1/schoolRank/schoolList' 
- [ ] 컬럼 추가로 인한 변경 사항들 생기면 변경!
   - [ ] /api/v1/schoolRank/firstRank
   - [ ] /api/v1/schoolRank/schoolList  
- [ ] 학교 검색시 관련 정보 추가하기

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
