### ISSUE TITLE
[feat] 학교 검색 api 개발진행

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#79]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

기획상황에 학교 검색을 추가하기로 하여 진행하기로함.

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] /api/v1/schoolRank/search 구현
- [x] 페이지네이션 적용하여 진행하기
- [x] 이전 검색로직 구현했던 사항 관련 참고하여 진행 #54 

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
