### ISSUE TITLE
[feat] 배포 환경 설정

### ISSUE THREAD

**Issue by khyojun** [capstone-kw-jjiggle/gitbal-be#99]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

.env, 등등 설정을 통해 미리 배포를 설정한다. profile 이용

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] profile 이용하여 운영 환경과 개발 환경을 분리한다.
- [x] .env 환경 변수를 이용하여 환경변수 처리를 한다.
- [x] docker-compose를 이용하여 앞으로 local, prod 환경을 분리하여 진행한다.
- [x] 작업 진행하면서 생겼던 오류들은 #117 에서 처리
- [x] 추가적으로 배포 진행!
## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- [배포관련 alpine jdk 문제 참고](https://github.com/adoptium/temurin-build/issues/2843)
-
